"""Update tables according to models 3

Revision ID: 332256f518eb
Revises: 4ce4cb846ab3
Create Date: 2024-10-21 23:25:49.565795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '332256f518eb'
down_revision: Union[str, None] = '4ce4cb846ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False, server_default='False'),
    sa.Column('blocked_', sa.Boolean(), nullable=False, server_default='False'),
    sa.Column('roles', sa.String(), nullable=False, server_default='Registered'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('working_time_start', sa.Time(), nullable=False),
    sa.Column('working_time_finish', sa.Time(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bars_name'), 'bars', ['name'], unique=False)

    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=11), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_index(op.f('ix_managers_fullName'), 'managers', ['fullName'], unique=False)
    op.create_index(op.f('ix_managers_phoneNumber'), 'managers', ['phoneNumber'], unique=True)

    op.create_table('barmen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('phoneNumber', sa.String(length=11), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_index(op.f('ix_barmen_fullName'), 'barmen', ['fullName'], unique=False)
    op.create_index(op.f('ix_barmen_phoneNumber'), 'barmen', ['phoneNumber'], unique=True)

    op.create_table('drinks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drinkName', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('drinkType', sa.String(), nullable=False),
    sa.Column('recipe', sa.String(), nullable=False),
    sa.Column('stock', sa.Boolean(), nullable=False, server_default='True'),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinks_drinkName'), 'drinks', ['drinkName'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drinks_drinkName'), table_name='drinks')
    op.drop_table('drinks')
    op.drop_index(op.f('ix_barmen_phoneNumber'), table_name='barmen')
    op.drop_index(op.f('ix_barmen_fullName'), table_name='barmen')
    op.drop_table('barmen')
    op.drop_index(op.f('ix_managers_phoneNumber'), table_name='managers')
    op.drop_index(op.f('ix_managers_fullName'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_bars_name'), table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
