"""Update tables according to models

Revision ID: 5724d93acf18
Revises: 69ceb2ace707
Create Date: 2024-10-21 21:01:16.251832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5724d93acf18'
down_revision: Union[str, None] = '69ceb2ace707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('password_', sa.String(), nullable=True),
        sa.Column('confirmed', sa.Boolean(), nullable=True),
        sa.Column('blocked_', sa.Boolean(), nullable=True),
        sa.Column('roles', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)

    op.create_table(
        'bars',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('working_time_start', sa.Time(), nullable=True),
        sa.Column('working_time_finish', sa.Time(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bars_id'), 'bars', ['id'], unique=False)
    op.create_index(op.f('ix_bars_name'), 'bars', ['name'], unique=False)

    op.create_table(
        'managers',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('fullName', sa.String(), nullable=True),
        sa.Column('phoneNumber', sa.String(length=11), nullable=True),
        sa.Column('bar_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_id'), 'managers', ['id'], unique=False)
    op.create_index(op.f('ix_managers_fullName'), 'managers', ['fullName'], unique=False)
    op.create_index(op.f('ix_managers_phoneNumber'), 'managers', ['phoneNumber'], unique=False)

    op.create_table(
        'barmen',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('fullName', sa.String(), nullable=True),
        sa.Column('phoneNumber', sa.String(length=11), nullable=True),
        sa.Column('bar_id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('manager_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
        sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barmen_id'), 'barmen', ['id'], unique=False)
    op.create_index(op.f('ix_barmen_fullName'), 'barmen', ['fullName'], unique=False)
    op.create_index(op.f('ix_barmen_phoneNumber'), 'barmen', ['phoneNumber'], unique=False)

    op.create_table(
        'drinks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('drinkName', sa.String(), nullable=True),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('drinkType', sa.String(), nullable=True),
        sa.Column('recipe', sa.String(), nullable=True),
        sa.Column('stock', sa.Boolean(), nullable=True),
        sa.Column('bar_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drinks_id'), 'drinks', ['id'], unique=False)
    op.create_index(op.f('ix_drinks_drinkName'), 'drinks', ['drinkName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drinks_drinkName'), table_name='drinks')
    op.drop_index(op.f('ix_drinks_id'), table_name='drinks')
    op.drop_table('drinks')
    op.drop_index(op.f('ix_barmen_phoneNumber'), table_name='barmen')
    op.drop_index(op.f('ix_barmen_fullName'), table_name='barmen')
    op.drop_index(op.f('ix_barmen_id'), table_name='barmen')
    op.drop_table('barmen')
    op.drop_index(op.f('ix_managers_phoneNumber'), table_name='managers')
    op.drop_index(op.f('ix_managers_fullName'), table_name='managers')
    op.drop_index(op.f('ix_managers_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_bars_name'), table_name='bars')
    op.drop_index(op.f('ix_bars_id'), table_name='bars')
    op.drop_table('bars')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###